model: "FasterSpeech"
sample_rate: 16000
labels: [
    " ", "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m",
    "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z", "'"
]

AudioToTextDataLayer:
    max_duration: 16.7
    trim_silence: true

    train:
        shuffle: true

    eval:
        shuffle: false
        max_duration: null

JasperEncoder:
    activation: "relu"
    conv_mask: true

    jasper:
        -   filters: 256
            repeat: 1
            kernel: [33]
            stride: [2]
            dilation: [1]
            dropout: 0.0
            residual: false
            separable: true

        -   filters: 256
            repeat: 5
            kernel: [33]
            stride: [1]
            dilation: [1]
            dropout: 0.0
            residual: true
            separable: true

        -   filters: 256
            repeat: 5
            kernel: [33]
            stride: [1]
            dilation: [1]
            dropout: 0.0
            residual: true
            separable: true

        -   filters: 256
            repeat: 5
            kernel: [33]
            stride: [1]
            dilation: [1]
            dropout: 0.0
            residual: true
            separable: true

        -   filters: 256
            repeat: 5
            kernel: [39]
            stride: [1]
            dilation: [1]
            dropout: 0.0
            residual: true
            separable: true

        -   filters: 256
            repeat: 5
            kernel: [39]
            stride: [1]
            dilation: [1]
            dropout: 0.0
            residual: true
            separable: true

        -   filters: 256
            repeat: 5
            kernel: [39]
            stride: [1]
            dilation: [1]
            dropout: 0.0
            residual: true
            separable: true

        -   filters: 512
            repeat: 5
            kernel: [51]
            stride: [1]
            dilation: [1]
            dropout: 0.0
            residual: true
            separable: true

        -   filters: 512
            repeat: 5
            kernel: [51]
            stride: [1]
            dilation: [1]
            dropout: 0.0
            residual: true
            separable: true

        -   filters: 512
            repeat: 5
            kernel: [51]
            stride: [1]
            dilation: [1]
            dropout: 0.0
            residual: true
            separable: true

        -   filters: 512
            repeat: 5
            kernel: [63]
            stride: [1]
            dilation: [1]
            dropout: 0.0
            residual: true
            separable: true

        -   filters: 512
            repeat: 5
            kernel: [63]
            stride: [1]
            dilation: [1]
            dropout: 0.0
            residual: true
            separable: true

        -   filters: 512
            repeat: 5
            kernel: [63]
            stride: [1]
            dilation: [1]
            dropout: 0.0
            residual: true
            separable: true

        -   filters: 512
            repeat: 5
            kernel: [75]
            stride: [1]
            dilation: [1]
            dropout: 0.0
            residual: true
            separable: true

        -   filters: 512
            repeat: 5
            kernel: [75]
            stride: [1]
            dilation: [1]
            dropout: 0.0
            residual: true
            separable: true

        -   filters: 512
            repeat: 5
            kernel: [75]
            stride: [1]
            dilation: [1]
            dropout: 0.0
            residual: true
            separable: true

        -   filters: 512
            repeat: 1
            kernel: [87]
            stride: [1]
            dilation: [2]
            dropout: 0.0
            residual: false
            separable: true

        -   filters: 1024
            repeat: 1
            kernel: [1]
            stride: [1]
            dilation: [1]
            dropout: 0.0
            residual: false